/*
Manage API

Testing PromoCodesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package management

import (
	"context"
	"testing"

	openapiclient "github.com/keboola/keboola-sdk-go/v2/pkg/keboola/management"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_management_PromoCodesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PromoCodesAPIService CreateNewPromoCodes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var maintainerId int32

		resp, httpRes, err := apiClient.PromoCodesAPI.CreateNewPromoCodes(context.Background(), maintainerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PromoCodesAPIService RetrieveAllPromoCodes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var maintainerId int32

		resp, httpRes, err := apiClient.PromoCodesAPI.RetrieveAllPromoCodes(context.Background(), maintainerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
