version: '3'
services:
  dev:
    image: keboolabot/keboola-sdk-go-dev
    build: .
    ports:
      - "6060:6060" #godoc
    volumes:
      - ./:/code:z
      - cache:/tmp/cache
    environment:
      - TEST_KBC_PROJECTS_FILE=/code/projects.json

volumes:
  cache:
