/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateANewBackend201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateANewBackend201Response{}

// CreateANewBackend201Response struct for CreateANewBackend201Response
type CreateANewBackend201Response struct {
	Id float32 `json:"id"`
	// 37-demo.cmizbsfmzc6w.us-east-1.redshift.amazonaws.com (required)
	Host *string `json:"host,omitempty"`
	Backend string `json:"backend"`
	// east-1
	Region *string `json:"region,omitempty"`
}

type _CreateANewBackend201Response CreateANewBackend201Response

// NewCreateANewBackend201Response instantiates a new CreateANewBackend201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateANewBackend201Response(id float32, backend string) *CreateANewBackend201Response {
	this := CreateANewBackend201Response{}
	this.Id = id
	this.Backend = backend
	return &this
}

// NewCreateANewBackend201ResponseWithDefaults instantiates a new CreateANewBackend201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateANewBackend201ResponseWithDefaults() *CreateANewBackend201Response {
	this := CreateANewBackend201Response{}
	return &this
}

// GetId returns the Id field value
func (o *CreateANewBackend201Response) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateANewBackend201Response) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateANewBackend201Response) SetId(v float32) {
	o.Id = v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *CreateANewBackend201Response) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateANewBackend201Response) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *CreateANewBackend201Response) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *CreateANewBackend201Response) SetHost(v string) {
	o.Host = &v
}

// GetBackend returns the Backend field value
func (o *CreateANewBackend201Response) GetBackend() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Backend
}

// GetBackendOk returns a tuple with the Backend field value
// and a boolean to check if the value has been set.
func (o *CreateANewBackend201Response) GetBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backend, true
}

// SetBackend sets field value
func (o *CreateANewBackend201Response) SetBackend(v string) {
	o.Backend = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CreateANewBackend201Response) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateANewBackend201Response) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CreateANewBackend201Response) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *CreateANewBackend201Response) SetRegion(v string) {
	o.Region = &v
}

func (o CreateANewBackend201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateANewBackend201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	toSerialize["backend"] = o.Backend
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

func (o *CreateANewBackend201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"backend",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateANewBackend201Response := _CreateANewBackend201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateANewBackend201Response)

	if err != nil {
		return err
	}

	*o = CreateANewBackend201Response(varCreateANewBackend201Response)

	return err
}

type NullableCreateANewBackend201Response struct {
	value *CreateANewBackend201Response
	isSet bool
}

func (v NullableCreateANewBackend201Response) Get() *CreateANewBackend201Response {
	return v.value
}

func (v *NullableCreateANewBackend201Response) Set(val *CreateANewBackend201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateANewBackend201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateANewBackend201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateANewBackend201Response(val *CreateANewBackend201Response) *NullableCreateANewBackend201Response {
	return &NullableCreateANewBackend201Response{value: val, isSet: true}
}

func (v NullableCreateANewBackend201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateANewBackend201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


