/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the ProjectModelPayAsYouGo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectModelPayAsYouGo{}

// ProjectModelPayAsYouGo struct for ProjectModelPayAsYouGo
type ProjectModelPayAsYouGo struct {
	PurchasedCredits *float32 `json:"purchasedCredits,omitempty"`
}

// NewProjectModelPayAsYouGo instantiates a new ProjectModelPayAsYouGo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectModelPayAsYouGo() *ProjectModelPayAsYouGo {
	this := ProjectModelPayAsYouGo{}
	return &this
}

// NewProjectModelPayAsYouGoWithDefaults instantiates a new ProjectModelPayAsYouGo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectModelPayAsYouGoWithDefaults() *ProjectModelPayAsYouGo {
	this := ProjectModelPayAsYouGo{}
	return &this
}

// GetPurchasedCredits returns the PurchasedCredits field value if set, zero value otherwise.
func (o *ProjectModelPayAsYouGo) GetPurchasedCredits() float32 {
	if o == nil || IsNil(o.PurchasedCredits) {
		var ret float32
		return ret
	}
	return *o.PurchasedCredits
}

// GetPurchasedCreditsOk returns a tuple with the PurchasedCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelPayAsYouGo) GetPurchasedCreditsOk() (*float32, bool) {
	if o == nil || IsNil(o.PurchasedCredits) {
		return nil, false
	}
	return o.PurchasedCredits, true
}

// HasPurchasedCredits returns a boolean if a field has been set.
func (o *ProjectModelPayAsYouGo) HasPurchasedCredits() bool {
	if o != nil && !IsNil(o.PurchasedCredits) {
		return true
	}

	return false
}

// SetPurchasedCredits gets a reference to the given float32 and assigns it to the PurchasedCredits field.
func (o *ProjectModelPayAsYouGo) SetPurchasedCredits(v float32) {
	o.PurchasedCredits = &v
}

func (o ProjectModelPayAsYouGo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectModelPayAsYouGo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PurchasedCredits) {
		toSerialize["purchasedCredits"] = o.PurchasedCredits
	}
	return toSerialize, nil
}

type NullableProjectModelPayAsYouGo struct {
	value *ProjectModelPayAsYouGo
	isSet bool
}

func (v NullableProjectModelPayAsYouGo) Get() *ProjectModelPayAsYouGo {
	return v.value
}

func (v *NullableProjectModelPayAsYouGo) Set(val *ProjectModelPayAsYouGo) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectModelPayAsYouGo) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectModelPayAsYouGo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectModelPayAsYouGo(val *ProjectModelPayAsYouGo) *NullableProjectModelPayAsYouGo {
	return &NullableProjectModelPayAsYouGo{value: val, isSet: true}
}

func (v NullableProjectModelPayAsYouGo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectModelPayAsYouGo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


