/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMaintainersInvitations200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMaintainersInvitations200ResponseInner{}

// ListMaintainersInvitations200ResponseInner struct for ListMaintainersInvitations200ResponseInner
type ListMaintainersInvitations200ResponseInner struct {
	Id float32 `json:"id"`
	Created string `json:"created"`
	User ListMaintainersInvitations200ResponseInnerUser `json:"user"`
	Creator ListMaintainersInvitations200ResponseInnerUser `json:"creator"`
}

type _ListMaintainersInvitations200ResponseInner ListMaintainersInvitations200ResponseInner

// NewListMaintainersInvitations200ResponseInner instantiates a new ListMaintainersInvitations200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMaintainersInvitations200ResponseInner(id float32, created string, user ListMaintainersInvitations200ResponseInnerUser, creator ListMaintainersInvitations200ResponseInnerUser) *ListMaintainersInvitations200ResponseInner {
	this := ListMaintainersInvitations200ResponseInner{}
	this.Id = id
	this.Created = created
	this.User = user
	this.Creator = creator
	return &this
}

// NewListMaintainersInvitations200ResponseInnerWithDefaults instantiates a new ListMaintainersInvitations200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMaintainersInvitations200ResponseInnerWithDefaults() *ListMaintainersInvitations200ResponseInner {
	this := ListMaintainersInvitations200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListMaintainersInvitations200ResponseInner) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListMaintainersInvitations200ResponseInner) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListMaintainersInvitations200ResponseInner) SetId(v float32) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *ListMaintainersInvitations200ResponseInner) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ListMaintainersInvitations200ResponseInner) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ListMaintainersInvitations200ResponseInner) SetCreated(v string) {
	o.Created = v
}

// GetUser returns the User field value
func (o *ListMaintainersInvitations200ResponseInner) GetUser() ListMaintainersInvitations200ResponseInnerUser {
	if o == nil {
		var ret ListMaintainersInvitations200ResponseInnerUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *ListMaintainersInvitations200ResponseInner) GetUserOk() (*ListMaintainersInvitations200ResponseInnerUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *ListMaintainersInvitations200ResponseInner) SetUser(v ListMaintainersInvitations200ResponseInnerUser) {
	o.User = v
}

// GetCreator returns the Creator field value
func (o *ListMaintainersInvitations200ResponseInner) GetCreator() ListMaintainersInvitations200ResponseInnerUser {
	if o == nil {
		var ret ListMaintainersInvitations200ResponseInnerUser
		return ret
	}

	return o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value
// and a boolean to check if the value has been set.
func (o *ListMaintainersInvitations200ResponseInner) GetCreatorOk() (*ListMaintainersInvitations200ResponseInnerUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Creator, true
}

// SetCreator sets field value
func (o *ListMaintainersInvitations200ResponseInner) SetCreator(v ListMaintainersInvitations200ResponseInnerUser) {
	o.Creator = v
}

func (o ListMaintainersInvitations200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMaintainersInvitations200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created"] = o.Created
	toSerialize["user"] = o.User
	toSerialize["creator"] = o.Creator
	return toSerialize, nil
}

func (o *ListMaintainersInvitations200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created",
		"user",
		"creator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMaintainersInvitations200ResponseInner := _ListMaintainersInvitations200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMaintainersInvitations200ResponseInner)

	if err != nil {
		return err
	}

	*o = ListMaintainersInvitations200ResponseInner(varListMaintainersInvitations200ResponseInner)

	return err
}

type NullableListMaintainersInvitations200ResponseInner struct {
	value *ListMaintainersInvitations200ResponseInner
	isSet bool
}

func (v NullableListMaintainersInvitations200ResponseInner) Get() *ListMaintainersInvitations200ResponseInner {
	return v.value
}

func (v *NullableListMaintainersInvitations200ResponseInner) Set(val *ListMaintainersInvitations200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListMaintainersInvitations200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListMaintainersInvitations200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMaintainersInvitations200ResponseInner(val *ListMaintainersInvitations200ResponseInner) *NullableListMaintainersInvitations200ResponseInner {
	return &NullableListMaintainersInvitations200ResponseInner{value: val, isSet: true}
}

func (v NullableListMaintainersInvitations200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMaintainersInvitations200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


