/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the RetrieveAnOrganization200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetrieveAnOrganization200Response{}

// RetrieveAnOrganization200Response struct for RetrieveAnOrganization200Response
type RetrieveAnOrganization200Response struct {
	Id *float32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Created *string `json:"created,omitempty"`
	AllowAutoJoin *bool `json:"allowAutoJoin,omitempty"`
	CrmId *string `json:"crmId,omitempty"`
	ActivityCenterProjectId *float32 `json:"activityCenterProjectId,omitempty"`
	MfaRequired *bool `json:"mfaRequired,omitempty"`
	Projects []RetrieveAnOrganization200ResponseProjectsInner `json:"projects,omitempty"`
}

// NewRetrieveAnOrganization200Response instantiates a new RetrieveAnOrganization200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetrieveAnOrganization200Response() *RetrieveAnOrganization200Response {
	this := RetrieveAnOrganization200Response{}
	return &this
}

// NewRetrieveAnOrganization200ResponseWithDefaults instantiates a new RetrieveAnOrganization200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetrieveAnOrganization200ResponseWithDefaults() *RetrieveAnOrganization200Response {
	this := RetrieveAnOrganization200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *RetrieveAnOrganization200Response) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RetrieveAnOrganization200Response) SetName(v string) {
	o.Name = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *RetrieveAnOrganization200Response) SetCreated(v string) {
	o.Created = &v
}

// GetAllowAutoJoin returns the AllowAutoJoin field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetAllowAutoJoin() bool {
	if o == nil || IsNil(o.AllowAutoJoin) {
		var ret bool
		return ret
	}
	return *o.AllowAutoJoin
}

// GetAllowAutoJoinOk returns a tuple with the AllowAutoJoin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetAllowAutoJoinOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowAutoJoin) {
		return nil, false
	}
	return o.AllowAutoJoin, true
}

// HasAllowAutoJoin returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasAllowAutoJoin() bool {
	if o != nil && !IsNil(o.AllowAutoJoin) {
		return true
	}

	return false
}

// SetAllowAutoJoin gets a reference to the given bool and assigns it to the AllowAutoJoin field.
func (o *RetrieveAnOrganization200Response) SetAllowAutoJoin(v bool) {
	o.AllowAutoJoin = &v
}

// GetCrmId returns the CrmId field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetCrmId() string {
	if o == nil || IsNil(o.CrmId) {
		var ret string
		return ret
	}
	return *o.CrmId
}

// GetCrmIdOk returns a tuple with the CrmId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetCrmIdOk() (*string, bool) {
	if o == nil || IsNil(o.CrmId) {
		return nil, false
	}
	return o.CrmId, true
}

// HasCrmId returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasCrmId() bool {
	if o != nil && !IsNil(o.CrmId) {
		return true
	}

	return false
}

// SetCrmId gets a reference to the given string and assigns it to the CrmId field.
func (o *RetrieveAnOrganization200Response) SetCrmId(v string) {
	o.CrmId = &v
}

// GetActivityCenterProjectId returns the ActivityCenterProjectId field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetActivityCenterProjectId() float32 {
	if o == nil || IsNil(o.ActivityCenterProjectId) {
		var ret float32
		return ret
	}
	return *o.ActivityCenterProjectId
}

// GetActivityCenterProjectIdOk returns a tuple with the ActivityCenterProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetActivityCenterProjectIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ActivityCenterProjectId) {
		return nil, false
	}
	return o.ActivityCenterProjectId, true
}

// HasActivityCenterProjectId returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasActivityCenterProjectId() bool {
	if o != nil && !IsNil(o.ActivityCenterProjectId) {
		return true
	}

	return false
}

// SetActivityCenterProjectId gets a reference to the given float32 and assigns it to the ActivityCenterProjectId field.
func (o *RetrieveAnOrganization200Response) SetActivityCenterProjectId(v float32) {
	o.ActivityCenterProjectId = &v
}

// GetMfaRequired returns the MfaRequired field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetMfaRequired() bool {
	if o == nil || IsNil(o.MfaRequired) {
		var ret bool
		return ret
	}
	return *o.MfaRequired
}

// GetMfaRequiredOk returns a tuple with the MfaRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetMfaRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.MfaRequired) {
		return nil, false
	}
	return o.MfaRequired, true
}

// HasMfaRequired returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasMfaRequired() bool {
	if o != nil && !IsNil(o.MfaRequired) {
		return true
	}

	return false
}

// SetMfaRequired gets a reference to the given bool and assigns it to the MfaRequired field.
func (o *RetrieveAnOrganization200Response) SetMfaRequired(v bool) {
	o.MfaRequired = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *RetrieveAnOrganization200Response) GetProjects() []RetrieveAnOrganization200ResponseProjectsInner {
	if o == nil || IsNil(o.Projects) {
		var ret []RetrieveAnOrganization200ResponseProjectsInner
		return ret
	}
	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveAnOrganization200Response) GetProjectsOk() ([]RetrieveAnOrganization200ResponseProjectsInner, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *RetrieveAnOrganization200Response) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given []RetrieveAnOrganization200ResponseProjectsInner and assigns it to the Projects field.
func (o *RetrieveAnOrganization200Response) SetProjects(v []RetrieveAnOrganization200ResponseProjectsInner) {
	o.Projects = v
}

func (o RetrieveAnOrganization200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetrieveAnOrganization200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.AllowAutoJoin) {
		toSerialize["allowAutoJoin"] = o.AllowAutoJoin
	}
	if !IsNil(o.CrmId) {
		toSerialize["crmId"] = o.CrmId
	}
	if !IsNil(o.ActivityCenterProjectId) {
		toSerialize["activityCenterProjectId"] = o.ActivityCenterProjectId
	}
	if !IsNil(o.MfaRequired) {
		toSerialize["mfaRequired"] = o.MfaRequired
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	return toSerialize, nil
}

type NullableRetrieveAnOrganization200Response struct {
	value *RetrieveAnOrganization200Response
	isSet bool
}

func (v NullableRetrieveAnOrganization200Response) Get() *RetrieveAnOrganization200Response {
	return v.value
}

func (v *NullableRetrieveAnOrganization200Response) Set(val *RetrieveAnOrganization200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRetrieveAnOrganization200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRetrieveAnOrganization200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetrieveAnOrganization200Response(val *RetrieveAnOrganization200Response) *NullableRetrieveAnOrganization200Response {
	return &NullableRetrieveAnOrganization200Response{value: val, isSet: true}
}

func (v NullableRetrieveAnOrganization200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetrieveAnOrganization200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


