/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the CreateAFeature201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAFeature201Response{}

// CreateAFeature201Response struct for CreateAFeature201Response
type CreateAFeature201Response struct {
	Id *float32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	CanBeManageByAdmin *bool `json:"canBeManageByAdmin,omitempty"`
	CanBeManagedViaAPI *bool `json:"canBeManagedViaAPI,omitempty"`
	Created *string `json:"created,omitempty"`
}

// NewCreateAFeature201Response instantiates a new CreateAFeature201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAFeature201Response() *CreateAFeature201Response {
	this := CreateAFeature201Response{}
	return &this
}

// NewCreateAFeature201ResponseWithDefaults instantiates a new CreateAFeature201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAFeature201ResponseWithDefaults() *CreateAFeature201Response {
	this := CreateAFeature201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *CreateAFeature201Response) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateAFeature201Response) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateAFeature201Response) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateAFeature201Response) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateAFeature201Response) SetDescription(v string) {
	o.Description = &v
}

// GetCanBeManageByAdmin returns the CanBeManageByAdmin field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetCanBeManageByAdmin() bool {
	if o == nil || IsNil(o.CanBeManageByAdmin) {
		var ret bool
		return ret
	}
	return *o.CanBeManageByAdmin
}

// GetCanBeManageByAdminOk returns a tuple with the CanBeManageByAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetCanBeManageByAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.CanBeManageByAdmin) {
		return nil, false
	}
	return o.CanBeManageByAdmin, true
}

// HasCanBeManageByAdmin returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasCanBeManageByAdmin() bool {
	if o != nil && !IsNil(o.CanBeManageByAdmin) {
		return true
	}

	return false
}

// SetCanBeManageByAdmin gets a reference to the given bool and assigns it to the CanBeManageByAdmin field.
func (o *CreateAFeature201Response) SetCanBeManageByAdmin(v bool) {
	o.CanBeManageByAdmin = &v
}

// GetCanBeManagedViaAPI returns the CanBeManagedViaAPI field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetCanBeManagedViaAPI() bool {
	if o == nil || IsNil(o.CanBeManagedViaAPI) {
		var ret bool
		return ret
	}
	return *o.CanBeManagedViaAPI
}

// GetCanBeManagedViaAPIOk returns a tuple with the CanBeManagedViaAPI field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetCanBeManagedViaAPIOk() (*bool, bool) {
	if o == nil || IsNil(o.CanBeManagedViaAPI) {
		return nil, false
	}
	return o.CanBeManagedViaAPI, true
}

// HasCanBeManagedViaAPI returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasCanBeManagedViaAPI() bool {
	if o != nil && !IsNil(o.CanBeManagedViaAPI) {
		return true
	}

	return false
}

// SetCanBeManagedViaAPI gets a reference to the given bool and assigns it to the CanBeManagedViaAPI field.
func (o *CreateAFeature201Response) SetCanBeManagedViaAPI(v bool) {
	o.CanBeManagedViaAPI = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *CreateAFeature201Response) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAFeature201Response) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *CreateAFeature201Response) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *CreateAFeature201Response) SetCreated(v string) {
	o.Created = &v
}

func (o CreateAFeature201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAFeature201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CanBeManageByAdmin) {
		toSerialize["canBeManageByAdmin"] = o.CanBeManageByAdmin
	}
	if !IsNil(o.CanBeManagedViaAPI) {
		toSerialize["canBeManagedViaAPI"] = o.CanBeManagedViaAPI
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	return toSerialize, nil
}

type NullableCreateAFeature201Response struct {
	value *CreateAFeature201Response
	isSet bool
}

func (v NullableCreateAFeature201Response) Get() *CreateAFeature201Response {
	return v.value
}

func (v *NullableCreateAFeature201Response) Set(val *CreateAFeature201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAFeature201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAFeature201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAFeature201Response(val *CreateAFeature201Response) *NullableCreateAFeature201Response {
	return &NullableCreateAFeature201Response{value: val, isSet: true}
}

func (v NullableCreateAFeature201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAFeature201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


