/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GiveCreditsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GiveCreditsRequest{}

// GiveCreditsRequest struct for GiveCreditsRequest
type GiveCreditsRequest struct {
	// Credits amount
	Amount float32 `json:"amount"`
	// Reason or label of given credits
	Description string `json:"description"`
}

type _GiveCreditsRequest GiveCreditsRequest

// NewGiveCreditsRequest instantiates a new GiveCreditsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGiveCreditsRequest(amount float32, description string) *GiveCreditsRequest {
	this := GiveCreditsRequest{}
	this.Amount = amount
	this.Description = description
	return &this
}

// NewGiveCreditsRequestWithDefaults instantiates a new GiveCreditsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGiveCreditsRequestWithDefaults() *GiveCreditsRequest {
	this := GiveCreditsRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *GiveCreditsRequest) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *GiveCreditsRequest) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *GiveCreditsRequest) SetAmount(v float32) {
	o.Amount = v
}

// GetDescription returns the Description field value
func (o *GiveCreditsRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GiveCreditsRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GiveCreditsRequest) SetDescription(v string) {
	o.Description = v
}

func (o GiveCreditsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GiveCreditsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *GiveCreditsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGiveCreditsRequest := _GiveCreditsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGiveCreditsRequest)

	if err != nil {
		return err
	}

	*o = GiveCreditsRequest(varGiveCreditsRequest)

	return err
}

type NullableGiveCreditsRequest struct {
	value *GiveCreditsRequest
	isSet bool
}

func (v NullableGiveCreditsRequest) Get() *GiveCreditsRequest {
	return v.value
}

func (v *NullableGiveCreditsRequest) Set(val *GiveCreditsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGiveCreditsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGiveCreditsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGiveCreditsRequest(val *GiveCreditsRequest) *NullableGiveCreditsRequest {
	return &NullableGiveCreditsRequest{value: val, isSet: true}
}

func (v NullableGiveCreditsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGiveCreditsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


