/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetMaintainerMetadataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetMaintainerMetadataRequest{}

// SetMaintainerMetadataRequest struct for SetMaintainerMetadataRequest
type SetMaintainerMetadataRequest struct {
	Provider string `json:"provider"`
	// Array of metadata objects
	Metadata []interface{} `json:"metadata"`
}

type _SetMaintainerMetadataRequest SetMaintainerMetadataRequest

// NewSetMaintainerMetadataRequest instantiates a new SetMaintainerMetadataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetMaintainerMetadataRequest(provider string, metadata []interface{}) *SetMaintainerMetadataRequest {
	this := SetMaintainerMetadataRequest{}
	this.Provider = provider
	this.Metadata = metadata
	return &this
}

// NewSetMaintainerMetadataRequestWithDefaults instantiates a new SetMaintainerMetadataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetMaintainerMetadataRequestWithDefaults() *SetMaintainerMetadataRequest {
	this := SetMaintainerMetadataRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *SetMaintainerMetadataRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *SetMaintainerMetadataRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *SetMaintainerMetadataRequest) SetProvider(v string) {
	o.Provider = v
}

// GetMetadata returns the Metadata field value
func (o *SetMaintainerMetadataRequest) GetMetadata() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *SetMaintainerMetadataRequest) GetMetadataOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *SetMaintainerMetadataRequest) SetMetadata(v []interface{}) {
	o.Metadata = v
}

func (o SetMaintainerMetadataRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetMaintainerMetadataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *SetMaintainerMetadataRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetMaintainerMetadataRequest := _SetMaintainerMetadataRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetMaintainerMetadataRequest)

	if err != nil {
		return err
	}

	*o = SetMaintainerMetadataRequest(varSetMaintainerMetadataRequest)

	return err
}

type NullableSetMaintainerMetadataRequest struct {
	value *SetMaintainerMetadataRequest
	isSet bool
}

func (v NullableSetMaintainerMetadataRequest) Get() *SetMaintainerMetadataRequest {
	return v.value
}

func (v *NullableSetMaintainerMetadataRequest) Set(val *SetMaintainerMetadataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetMaintainerMetadataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetMaintainerMetadataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetMaintainerMetadataRequest(val *SetMaintainerMetadataRequest) *NullableSetMaintainerMetadataRequest {
	return &NullableSetMaintainerMetadataRequest{value: val, isSet: true}
}

func (v NullableSetMaintainerMetadataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetMaintainerMetadataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


