/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the RegisterNewApplicationVersion201ResponseApp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterNewApplicationVersion201ResponseApp{}

// RegisterNewApplicationVersion201ResponseApp struct for RegisterNewApplicationVersion201ResponseApp
type RegisterNewApplicationVersion201ResponseApp struct {
	Id *string `json:"id,omitempty"`
	StringId *string `json:"stringId,omitempty"`
	Name *string `json:"name,omitempty"`
	Created *string `json:"created,omitempty"`
}

// NewRegisterNewApplicationVersion201ResponseApp instantiates a new RegisterNewApplicationVersion201ResponseApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterNewApplicationVersion201ResponseApp() *RegisterNewApplicationVersion201ResponseApp {
	this := RegisterNewApplicationVersion201ResponseApp{}
	return &this
}

// NewRegisterNewApplicationVersion201ResponseAppWithDefaults instantiates a new RegisterNewApplicationVersion201ResponseApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterNewApplicationVersion201ResponseAppWithDefaults() *RegisterNewApplicationVersion201ResponseApp {
	this := RegisterNewApplicationVersion201ResponseApp{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegisterNewApplicationVersion201ResponseApp) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RegisterNewApplicationVersion201ResponseApp) SetId(v string) {
	o.Id = &v
}

// GetStringId returns the StringId field value if set, zero value otherwise.
func (o *RegisterNewApplicationVersion201ResponseApp) GetStringId() string {
	if o == nil || IsNil(o.StringId) {
		var ret string
		return ret
	}
	return *o.StringId
}

// GetStringIdOk returns a tuple with the StringId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) GetStringIdOk() (*string, bool) {
	if o == nil || IsNil(o.StringId) {
		return nil, false
	}
	return o.StringId, true
}

// HasStringId returns a boolean if a field has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) HasStringId() bool {
	if o != nil && !IsNil(o.StringId) {
		return true
	}

	return false
}

// SetStringId gets a reference to the given string and assigns it to the StringId field.
func (o *RegisterNewApplicationVersion201ResponseApp) SetStringId(v string) {
	o.StringId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RegisterNewApplicationVersion201ResponseApp) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RegisterNewApplicationVersion201ResponseApp) SetName(v string) {
	o.Name = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *RegisterNewApplicationVersion201ResponseApp) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *RegisterNewApplicationVersion201ResponseApp) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *RegisterNewApplicationVersion201ResponseApp) SetCreated(v string) {
	o.Created = &v
}

func (o RegisterNewApplicationVersion201ResponseApp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterNewApplicationVersion201ResponseApp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.StringId) {
		toSerialize["stringId"] = o.StringId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	return toSerialize, nil
}

type NullableRegisterNewApplicationVersion201ResponseApp struct {
	value *RegisterNewApplicationVersion201ResponseApp
	isSet bool
}

func (v NullableRegisterNewApplicationVersion201ResponseApp) Get() *RegisterNewApplicationVersion201ResponseApp {
	return v.value
}

func (v *NullableRegisterNewApplicationVersion201ResponseApp) Set(val *RegisterNewApplicationVersion201ResponseApp) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterNewApplicationVersion201ResponseApp) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterNewApplicationVersion201ResponseApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterNewApplicationVersion201ResponseApp(val *RegisterNewApplicationVersion201ResponseApp) *NullableRegisterNewApplicationVersion201ResponseApp {
	return &NullableRegisterNewApplicationVersion201ResponseApp{value: val, isSet: true}
}

func (v NullableRegisterNewApplicationVersion201ResponseApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterNewApplicationVersion201ResponseApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


