/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the ProjectModelFileStorage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectModelFileStorage{}

// ProjectModelFileStorage struct for ProjectModelFileStorage
type ProjectModelFileStorage struct {
	Id *float32 `json:"id,omitempty"`
	AwsKey *string `json:"awsKey,omitempty"`
	Region *string `json:"region,omitempty"`
	FilesBucket *string `json:"filesBucket,omitempty"`
	Owner *string `json:"owner,omitempty"`
	IsDefault *bool `json:"isDefault,omitempty"`
	Created *string `json:"created,omitempty"`
	Creator *ProjectModelFileStorageCreator `json:"creator,omitempty"`
}

// NewProjectModelFileStorage instantiates a new ProjectModelFileStorage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectModelFileStorage() *ProjectModelFileStorage {
	this := ProjectModelFileStorage{}
	return &this
}

// NewProjectModelFileStorageWithDefaults instantiates a new ProjectModelFileStorage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectModelFileStorageWithDefaults() *ProjectModelFileStorage {
	this := ProjectModelFileStorage{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *ProjectModelFileStorage) SetId(v float32) {
	o.Id = &v
}

// GetAwsKey returns the AwsKey field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetAwsKey() string {
	if o == nil || IsNil(o.AwsKey) {
		var ret string
		return ret
	}
	return *o.AwsKey
}

// GetAwsKeyOk returns a tuple with the AwsKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetAwsKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AwsKey) {
		return nil, false
	}
	return o.AwsKey, true
}

// HasAwsKey returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasAwsKey() bool {
	if o != nil && !IsNil(o.AwsKey) {
		return true
	}

	return false
}

// SetAwsKey gets a reference to the given string and assigns it to the AwsKey field.
func (o *ProjectModelFileStorage) SetAwsKey(v string) {
	o.AwsKey = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ProjectModelFileStorage) SetRegion(v string) {
	o.Region = &v
}

// GetFilesBucket returns the FilesBucket field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetFilesBucket() string {
	if o == nil || IsNil(o.FilesBucket) {
		var ret string
		return ret
	}
	return *o.FilesBucket
}

// GetFilesBucketOk returns a tuple with the FilesBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetFilesBucketOk() (*string, bool) {
	if o == nil || IsNil(o.FilesBucket) {
		return nil, false
	}
	return o.FilesBucket, true
}

// HasFilesBucket returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasFilesBucket() bool {
	if o != nil && !IsNil(o.FilesBucket) {
		return true
	}

	return false
}

// SetFilesBucket gets a reference to the given string and assigns it to the FilesBucket field.
func (o *ProjectModelFileStorage) SetFilesBucket(v string) {
	o.FilesBucket = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *ProjectModelFileStorage) SetOwner(v string) {
	o.Owner = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *ProjectModelFileStorage) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *ProjectModelFileStorage) SetCreated(v string) {
	o.Created = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *ProjectModelFileStorage) GetCreator() ProjectModelFileStorageCreator {
	if o == nil || IsNil(o.Creator) {
		var ret ProjectModelFileStorageCreator
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectModelFileStorage) GetCreatorOk() (*ProjectModelFileStorageCreator, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *ProjectModelFileStorage) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given ProjectModelFileStorageCreator and assigns it to the Creator field.
func (o *ProjectModelFileStorage) SetCreator(v ProjectModelFileStorageCreator) {
	o.Creator = &v
}

func (o ProjectModelFileStorage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectModelFileStorage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AwsKey) {
		toSerialize["awsKey"] = o.AwsKey
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.FilesBucket) {
		toSerialize["filesBucket"] = o.FilesBucket
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	return toSerialize, nil
}

type NullableProjectModelFileStorage struct {
	value *ProjectModelFileStorage
	isSet bool
}

func (v NullableProjectModelFileStorage) Get() *ProjectModelFileStorage {
	return v.value
}

func (v *NullableProjectModelFileStorage) Set(val *ProjectModelFileStorage) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectModelFileStorage) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectModelFileStorage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectModelFileStorage(val *ProjectModelFileStorage) *NullableProjectModelFileStorage {
	return &NullableProjectModelFileStorage{value: val, isSet: true}
}

func (v NullableProjectModelFileStorage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectModelFileStorage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


