/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the JoinRequestDetail200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JoinRequestDetail200Response{}

// JoinRequestDetail200Response struct for JoinRequestDetail200Response
type JoinRequestDetail200Response struct {
	Id *float32 `json:"id,omitempty"`
	Created *string `json:"created,omitempty"`
	Expires interface{} `json:"expires,omitempty"`
	Reason *string `json:"reason,omitempty"`
	User *ListMaintainersInvitations200ResponseInnerUser `json:"user,omitempty"`
}

// NewJoinRequestDetail200Response instantiates a new JoinRequestDetail200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJoinRequestDetail200Response() *JoinRequestDetail200Response {
	this := JoinRequestDetail200Response{}
	return &this
}

// NewJoinRequestDetail200ResponseWithDefaults instantiates a new JoinRequestDetail200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJoinRequestDetail200ResponseWithDefaults() *JoinRequestDetail200Response {
	this := JoinRequestDetail200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *JoinRequestDetail200Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JoinRequestDetail200Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *JoinRequestDetail200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *JoinRequestDetail200Response) SetId(v float32) {
	o.Id = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *JoinRequestDetail200Response) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JoinRequestDetail200Response) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *JoinRequestDetail200Response) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *JoinRequestDetail200Response) SetCreated(v string) {
	o.Created = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JoinRequestDetail200Response) GetExpires() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JoinRequestDetail200Response) GetExpiresOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return &o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *JoinRequestDetail200Response) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given interface{} and assigns it to the Expires field.
func (o *JoinRequestDetail200Response) SetExpires(v interface{}) {
	o.Expires = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *JoinRequestDetail200Response) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JoinRequestDetail200Response) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *JoinRequestDetail200Response) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *JoinRequestDetail200Response) SetReason(v string) {
	o.Reason = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *JoinRequestDetail200Response) GetUser() ListMaintainersInvitations200ResponseInnerUser {
	if o == nil || IsNil(o.User) {
		var ret ListMaintainersInvitations200ResponseInnerUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JoinRequestDetail200Response) GetUserOk() (*ListMaintainersInvitations200ResponseInnerUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *JoinRequestDetail200Response) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given ListMaintainersInvitations200ResponseInnerUser and assigns it to the User field.
func (o *JoinRequestDetail200Response) SetUser(v ListMaintainersInvitations200ResponseInnerUser) {
	o.User = &v
}

func (o JoinRequestDetail200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JoinRequestDetail200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if o.Expires != nil {
		toSerialize["expires"] = o.Expires
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableJoinRequestDetail200Response struct {
	value *JoinRequestDetail200Response
	isSet bool
}

func (v NullableJoinRequestDetail200Response) Get() *JoinRequestDetail200Response {
	return v.value
}

func (v *NullableJoinRequestDetail200Response) Set(val *JoinRequestDetail200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableJoinRequestDetail200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableJoinRequestDetail200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJoinRequestDetail200Response(val *JoinRequestDetail200Response) *NullableJoinRequestDetail200Response {
	return &NullableJoinRequestDetail200Response{value: val, isSet: true}
}

func (v NullableJoinRequestDetail200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJoinRequestDetail200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


