/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssignProjectStorageBackendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignProjectStorageBackendRequest{}

// AssignProjectStorageBackendRequest struct for AssignProjectStorageBackendRequest
type AssignProjectStorageBackendRequest struct {
	// ID of Storage backend
	StorageBackendId string `json:"storageBackendId"`
}

type _AssignProjectStorageBackendRequest AssignProjectStorageBackendRequest

// NewAssignProjectStorageBackendRequest instantiates a new AssignProjectStorageBackendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignProjectStorageBackendRequest(storageBackendId string) *AssignProjectStorageBackendRequest {
	this := AssignProjectStorageBackendRequest{}
	this.StorageBackendId = storageBackendId
	return &this
}

// NewAssignProjectStorageBackendRequestWithDefaults instantiates a new AssignProjectStorageBackendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignProjectStorageBackendRequestWithDefaults() *AssignProjectStorageBackendRequest {
	this := AssignProjectStorageBackendRequest{}
	return &this
}

// GetStorageBackendId returns the StorageBackendId field value
func (o *AssignProjectStorageBackendRequest) GetStorageBackendId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageBackendId
}

// GetStorageBackendIdOk returns a tuple with the StorageBackendId field value
// and a boolean to check if the value has been set.
func (o *AssignProjectStorageBackendRequest) GetStorageBackendIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageBackendId, true
}

// SetStorageBackendId sets field value
func (o *AssignProjectStorageBackendRequest) SetStorageBackendId(v string) {
	o.StorageBackendId = v
}

func (o AssignProjectStorageBackendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignProjectStorageBackendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["storageBackendId"] = o.StorageBackendId
	return toSerialize, nil
}

func (o *AssignProjectStorageBackendRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storageBackendId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssignProjectStorageBackendRequest := _AssignProjectStorageBackendRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssignProjectStorageBackendRequest)

	if err != nil {
		return err
	}

	*o = AssignProjectStorageBackendRequest(varAssignProjectStorageBackendRequest)

	return err
}

type NullableAssignProjectStorageBackendRequest struct {
	value *AssignProjectStorageBackendRequest
	isSet bool
}

func (v NullableAssignProjectStorageBackendRequest) Get() *AssignProjectStorageBackendRequest {
	return v.value
}

func (v *NullableAssignProjectStorageBackendRequest) Set(val *AssignProjectStorageBackendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignProjectStorageBackendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignProjectStorageBackendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignProjectStorageBackendRequest(val *AssignProjectStorageBackendRequest) *NullableAssignProjectStorageBackendRequest {
	return &NullableAssignProjectStorageBackendRequest{value: val, isSet: true}
}

func (v NullableAssignProjectStorageBackendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignProjectStorageBackendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


