/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the InviteAUserToAMaintainer201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteAUserToAMaintainer201Response{}

// InviteAUserToAMaintainer201Response struct for InviteAUserToAMaintainer201Response
type InviteAUserToAMaintainer201Response struct {
	Id *float32 `json:"id,omitempty"`
	Created *string `json:"created,omitempty"`
	User *ListMaintainersInvitations200ResponseInnerUser `json:"user,omitempty"`
	Creator *ListMaintainersInvitations200ResponseInnerUser `json:"creator,omitempty"`
}

// NewInviteAUserToAMaintainer201Response instantiates a new InviteAUserToAMaintainer201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteAUserToAMaintainer201Response() *InviteAUserToAMaintainer201Response {
	this := InviteAUserToAMaintainer201Response{}
	return &this
}

// NewInviteAUserToAMaintainer201ResponseWithDefaults instantiates a new InviteAUserToAMaintainer201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteAUserToAMaintainer201ResponseWithDefaults() *InviteAUserToAMaintainer201Response {
	this := InviteAUserToAMaintainer201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InviteAUserToAMaintainer201Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteAUserToAMaintainer201Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InviteAUserToAMaintainer201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *InviteAUserToAMaintainer201Response) SetId(v float32) {
	o.Id = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *InviteAUserToAMaintainer201Response) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteAUserToAMaintainer201Response) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *InviteAUserToAMaintainer201Response) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *InviteAUserToAMaintainer201Response) SetCreated(v string) {
	o.Created = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *InviteAUserToAMaintainer201Response) GetUser() ListMaintainersInvitations200ResponseInnerUser {
	if o == nil || IsNil(o.User) {
		var ret ListMaintainersInvitations200ResponseInnerUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteAUserToAMaintainer201Response) GetUserOk() (*ListMaintainersInvitations200ResponseInnerUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *InviteAUserToAMaintainer201Response) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given ListMaintainersInvitations200ResponseInnerUser and assigns it to the User field.
func (o *InviteAUserToAMaintainer201Response) SetUser(v ListMaintainersInvitations200ResponseInnerUser) {
	o.User = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *InviteAUserToAMaintainer201Response) GetCreator() ListMaintainersInvitations200ResponseInnerUser {
	if o == nil || IsNil(o.Creator) {
		var ret ListMaintainersInvitations200ResponseInnerUser
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteAUserToAMaintainer201Response) GetCreatorOk() (*ListMaintainersInvitations200ResponseInnerUser, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *InviteAUserToAMaintainer201Response) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given ListMaintainersInvitations200ResponseInnerUser and assigns it to the Creator field.
func (o *InviteAUserToAMaintainer201Response) SetCreator(v ListMaintainersInvitations200ResponseInnerUser) {
	o.Creator = &v
}

func (o InviteAUserToAMaintainer201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteAUserToAMaintainer201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	return toSerialize, nil
}

type NullableInviteAUserToAMaintainer201Response struct {
	value *InviteAUserToAMaintainer201Response
	isSet bool
}

func (v NullableInviteAUserToAMaintainer201Response) Get() *InviteAUserToAMaintainer201Response {
	return v.value
}

func (v *NullableInviteAUserToAMaintainer201Response) Set(val *InviteAUserToAMaintainer201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteAUserToAMaintainer201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteAUserToAMaintainer201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteAUserToAMaintainer201Response(val *InviteAUserToAMaintainer201Response) *NullableInviteAUserToAMaintainer201Response {
	return &NullableInviteAUserToAMaintainer201Response{value: val, isSet: true}
}

func (v NullableInviteAUserToAMaintainer201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteAUserToAMaintainer201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


