/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the ChangeProjectDisabledStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeProjectDisabledStatusRequest{}

// ChangeProjectDisabledStatusRequest struct for ChangeProjectDisabledStatusRequest
type ChangeProjectDisabledStatusRequest struct {
	// Enable or disable project
	IsDisabled *bool `json:"isDisabled,omitempty"`
	// Why the project is disabled
	DisableReason *string `json:"disableReason,omitempty"`
	// When the project will be enabled
	EstimatedEndTime *string `json:"estimatedEndTime,omitempty"`
}

// NewChangeProjectDisabledStatusRequest instantiates a new ChangeProjectDisabledStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeProjectDisabledStatusRequest() *ChangeProjectDisabledStatusRequest {
	this := ChangeProjectDisabledStatusRequest{}
	return &this
}

// NewChangeProjectDisabledStatusRequestWithDefaults instantiates a new ChangeProjectDisabledStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeProjectDisabledStatusRequestWithDefaults() *ChangeProjectDisabledStatusRequest {
	this := ChangeProjectDisabledStatusRequest{}
	return &this
}

// GetIsDisabled returns the IsDisabled field value if set, zero value otherwise.
func (o *ChangeProjectDisabledStatusRequest) GetIsDisabled() bool {
	if o == nil || IsNil(o.IsDisabled) {
		var ret bool
		return ret
	}
	return *o.IsDisabled
}

// GetIsDisabledOk returns a tuple with the IsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeProjectDisabledStatusRequest) GetIsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDisabled) {
		return nil, false
	}
	return o.IsDisabled, true
}

// HasIsDisabled returns a boolean if a field has been set.
func (o *ChangeProjectDisabledStatusRequest) HasIsDisabled() bool {
	if o != nil && !IsNil(o.IsDisabled) {
		return true
	}

	return false
}

// SetIsDisabled gets a reference to the given bool and assigns it to the IsDisabled field.
func (o *ChangeProjectDisabledStatusRequest) SetIsDisabled(v bool) {
	o.IsDisabled = &v
}

// GetDisableReason returns the DisableReason field value if set, zero value otherwise.
func (o *ChangeProjectDisabledStatusRequest) GetDisableReason() string {
	if o == nil || IsNil(o.DisableReason) {
		var ret string
		return ret
	}
	return *o.DisableReason
}

// GetDisableReasonOk returns a tuple with the DisableReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeProjectDisabledStatusRequest) GetDisableReasonOk() (*string, bool) {
	if o == nil || IsNil(o.DisableReason) {
		return nil, false
	}
	return o.DisableReason, true
}

// HasDisableReason returns a boolean if a field has been set.
func (o *ChangeProjectDisabledStatusRequest) HasDisableReason() bool {
	if o != nil && !IsNil(o.DisableReason) {
		return true
	}

	return false
}

// SetDisableReason gets a reference to the given string and assigns it to the DisableReason field.
func (o *ChangeProjectDisabledStatusRequest) SetDisableReason(v string) {
	o.DisableReason = &v
}

// GetEstimatedEndTime returns the EstimatedEndTime field value if set, zero value otherwise.
func (o *ChangeProjectDisabledStatusRequest) GetEstimatedEndTime() string {
	if o == nil || IsNil(o.EstimatedEndTime) {
		var ret string
		return ret
	}
	return *o.EstimatedEndTime
}

// GetEstimatedEndTimeOk returns a tuple with the EstimatedEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeProjectDisabledStatusRequest) GetEstimatedEndTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedEndTime) {
		return nil, false
	}
	return o.EstimatedEndTime, true
}

// HasEstimatedEndTime returns a boolean if a field has been set.
func (o *ChangeProjectDisabledStatusRequest) HasEstimatedEndTime() bool {
	if o != nil && !IsNil(o.EstimatedEndTime) {
		return true
	}

	return false
}

// SetEstimatedEndTime gets a reference to the given string and assigns it to the EstimatedEndTime field.
func (o *ChangeProjectDisabledStatusRequest) SetEstimatedEndTime(v string) {
	o.EstimatedEndTime = &v
}

func (o ChangeProjectDisabledStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeProjectDisabledStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsDisabled) {
		toSerialize["isDisabled"] = o.IsDisabled
	}
	if !IsNil(o.DisableReason) {
		toSerialize["disableReason"] = o.DisableReason
	}
	if !IsNil(o.EstimatedEndTime) {
		toSerialize["estimatedEndTime"] = o.EstimatedEndTime
	}
	return toSerialize, nil
}

type NullableChangeProjectDisabledStatusRequest struct {
	value *ChangeProjectDisabledStatusRequest
	isSet bool
}

func (v NullableChangeProjectDisabledStatusRequest) Get() *ChangeProjectDisabledStatusRequest {
	return v.value
}

func (v *NullableChangeProjectDisabledStatusRequest) Set(val *ChangeProjectDisabledStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeProjectDisabledStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeProjectDisabledStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeProjectDisabledStatusRequest(val *ChangeProjectDisabledStatusRequest) *NullableChangeProjectDisabledStatusRequest {
	return &NullableChangeProjectDisabledStatusRequest{value: val, isSet: true}
}

func (v NullableChangeProjectDisabledStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeProjectDisabledStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


