/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssignProjectFileStorageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignProjectFileStorageRequest{}

// AssignProjectFileStorageRequest struct for AssignProjectFileStorageRequest
type AssignProjectFileStorageRequest struct {
	// ID of file Storage
	FileStorageId string `json:"fileStorageId"`
}

type _AssignProjectFileStorageRequest AssignProjectFileStorageRequest

// NewAssignProjectFileStorageRequest instantiates a new AssignProjectFileStorageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignProjectFileStorageRequest(fileStorageId string) *AssignProjectFileStorageRequest {
	this := AssignProjectFileStorageRequest{}
	this.FileStorageId = fileStorageId
	return &this
}

// NewAssignProjectFileStorageRequestWithDefaults instantiates a new AssignProjectFileStorageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignProjectFileStorageRequestWithDefaults() *AssignProjectFileStorageRequest {
	this := AssignProjectFileStorageRequest{}
	return &this
}

// GetFileStorageId returns the FileStorageId field value
func (o *AssignProjectFileStorageRequest) GetFileStorageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileStorageId
}

// GetFileStorageIdOk returns a tuple with the FileStorageId field value
// and a boolean to check if the value has been set.
func (o *AssignProjectFileStorageRequest) GetFileStorageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileStorageId, true
}

// SetFileStorageId sets field value
func (o *AssignProjectFileStorageRequest) SetFileStorageId(v string) {
	o.FileStorageId = v
}

func (o AssignProjectFileStorageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignProjectFileStorageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fileStorageId"] = o.FileStorageId
	return toSerialize, nil
}

func (o *AssignProjectFileStorageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fileStorageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssignProjectFileStorageRequest := _AssignProjectFileStorageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssignProjectFileStorageRequest)

	if err != nil {
		return err
	}

	*o = AssignProjectFileStorageRequest(varAssignProjectFileStorageRequest)

	return err
}

type NullableAssignProjectFileStorageRequest struct {
	value *AssignProjectFileStorageRequest
	isSet bool
}

func (v NullableAssignProjectFileStorageRequest) Get() *AssignProjectFileStorageRequest {
	return v.value
}

func (v *NullableAssignProjectFileStorageRequest) Set(val *AssignProjectFileStorageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignProjectFileStorageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignProjectFileStorageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignProjectFileStorageRequest(val *AssignProjectFileStorageRequest) *NullableAssignProjectFileStorageRequest {
	return &NullableAssignProjectFileStorageRequest{value: val, isSet: true}
}

func (v NullableAssignProjectFileStorageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignProjectFileStorageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


