/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddAProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAProjectRequest{}

// AddAProjectRequest struct for AddAProjectRequest
type AddAProjectRequest struct {
	// Project name
	Name string `json:"name"`
	// One of `production`, `poc`, `demo`; default is `production`
	Type string `json:"type"`
	// Project default backend `snowflake` or `redshift`; default is `snowflake`
	DefaultBackend *string `json:"defaultBackend,omitempty"`
	// Data retention in days for Time Travel
	DataRetentionTimeInDays *string `json:"dataRetentionTimeInDays,omitempty"`
}

type _AddAProjectRequest AddAProjectRequest

// NewAddAProjectRequest instantiates a new AddAProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAProjectRequest(name string, type_ string) *AddAProjectRequest {
	this := AddAProjectRequest{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewAddAProjectRequestWithDefaults instantiates a new AddAProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAProjectRequestWithDefaults() *AddAProjectRequest {
	this := AddAProjectRequest{}
	return &this
}

// GetName returns the Name field value
func (o *AddAProjectRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddAProjectRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddAProjectRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *AddAProjectRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AddAProjectRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AddAProjectRequest) SetType(v string) {
	o.Type = v
}

// GetDefaultBackend returns the DefaultBackend field value if set, zero value otherwise.
func (o *AddAProjectRequest) GetDefaultBackend() string {
	if o == nil || IsNil(o.DefaultBackend) {
		var ret string
		return ret
	}
	return *o.DefaultBackend
}

// GetDefaultBackendOk returns a tuple with the DefaultBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAProjectRequest) GetDefaultBackendOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultBackend) {
		return nil, false
	}
	return o.DefaultBackend, true
}

// HasDefaultBackend returns a boolean if a field has been set.
func (o *AddAProjectRequest) HasDefaultBackend() bool {
	if o != nil && !IsNil(o.DefaultBackend) {
		return true
	}

	return false
}

// SetDefaultBackend gets a reference to the given string and assigns it to the DefaultBackend field.
func (o *AddAProjectRequest) SetDefaultBackend(v string) {
	o.DefaultBackend = &v
}

// GetDataRetentionTimeInDays returns the DataRetentionTimeInDays field value if set, zero value otherwise.
func (o *AddAProjectRequest) GetDataRetentionTimeInDays() string {
	if o == nil || IsNil(o.DataRetentionTimeInDays) {
		var ret string
		return ret
	}
	return *o.DataRetentionTimeInDays
}

// GetDataRetentionTimeInDaysOk returns a tuple with the DataRetentionTimeInDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAProjectRequest) GetDataRetentionTimeInDaysOk() (*string, bool) {
	if o == nil || IsNil(o.DataRetentionTimeInDays) {
		return nil, false
	}
	return o.DataRetentionTimeInDays, true
}

// HasDataRetentionTimeInDays returns a boolean if a field has been set.
func (o *AddAProjectRequest) HasDataRetentionTimeInDays() bool {
	if o != nil && !IsNil(o.DataRetentionTimeInDays) {
		return true
	}

	return false
}

// SetDataRetentionTimeInDays gets a reference to the given string and assigns it to the DataRetentionTimeInDays field.
func (o *AddAProjectRequest) SetDataRetentionTimeInDays(v string) {
	o.DataRetentionTimeInDays = &v
}

func (o AddAProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.DefaultBackend) {
		toSerialize["defaultBackend"] = o.DefaultBackend
	}
	if !IsNil(o.DataRetentionTimeInDays) {
		toSerialize["dataRetentionTimeInDays"] = o.DataRetentionTimeInDays
	}
	return toSerialize, nil
}

func (o *AddAProjectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddAProjectRequest := _AddAProjectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddAProjectRequest)

	if err != nil {
		return err
	}

	*o = AddAProjectRequest(varAddAProjectRequest)

	return err
}

type NullableAddAProjectRequest struct {
	value *AddAProjectRequest
	isSet bool
}

func (v NullableAddAProjectRequest) Get() *AddAProjectRequest {
	return v.value
}

func (v *NullableAddAProjectRequest) Set(val *AddAProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAProjectRequest(val *AddAProjectRequest) *NullableAddAProjectRequest {
	return &NullableAddAProjectRequest{value: val, isSet: true}
}

func (v NullableAddAProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


