/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the JoinAProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JoinAProjectRequest{}

// JoinAProjectRequest struct for JoinAProjectRequest
type JoinAProjectRequest struct {
	// Reason for joining the project
	Reason *string `json:"reason,omitempty"`
	// The number of seconds until the user's membership expires
	ExpirationSeconds *float32 `json:"expirationSeconds,omitempty"`
}

// NewJoinAProjectRequest instantiates a new JoinAProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJoinAProjectRequest() *JoinAProjectRequest {
	this := JoinAProjectRequest{}
	return &this
}

// NewJoinAProjectRequestWithDefaults instantiates a new JoinAProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJoinAProjectRequestWithDefaults() *JoinAProjectRequest {
	this := JoinAProjectRequest{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *JoinAProjectRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JoinAProjectRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *JoinAProjectRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *JoinAProjectRequest) SetReason(v string) {
	o.Reason = &v
}

// GetExpirationSeconds returns the ExpirationSeconds field value if set, zero value otherwise.
func (o *JoinAProjectRequest) GetExpirationSeconds() float32 {
	if o == nil || IsNil(o.ExpirationSeconds) {
		var ret float32
		return ret
	}
	return *o.ExpirationSeconds
}

// GetExpirationSecondsOk returns a tuple with the ExpirationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JoinAProjectRequest) GetExpirationSecondsOk() (*float32, bool) {
	if o == nil || IsNil(o.ExpirationSeconds) {
		return nil, false
	}
	return o.ExpirationSeconds, true
}

// HasExpirationSeconds returns a boolean if a field has been set.
func (o *JoinAProjectRequest) HasExpirationSeconds() bool {
	if o != nil && !IsNil(o.ExpirationSeconds) {
		return true
	}

	return false
}

// SetExpirationSeconds gets a reference to the given float32 and assigns it to the ExpirationSeconds field.
func (o *JoinAProjectRequest) SetExpirationSeconds(v float32) {
	o.ExpirationSeconds = &v
}

func (o JoinAProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JoinAProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.ExpirationSeconds) {
		toSerialize["expirationSeconds"] = o.ExpirationSeconds
	}
	return toSerialize, nil
}

type NullableJoinAProjectRequest struct {
	value *JoinAProjectRequest
	isSet bool
}

func (v NullableJoinAProjectRequest) Get() *JoinAProjectRequest {
	return v.value
}

func (v *NullableJoinAProjectRequest) Set(val *JoinAProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJoinAProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJoinAProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJoinAProjectRequest(val *JoinAProjectRequest) *NullableJoinAProjectRequest {
	return &NullableJoinAProjectRequest{value: val, isSet: true}
}

func (v NullableJoinAProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJoinAProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


