/*
Manage API

The Keboola Connection Management API covers all tasks required for managing projects, as well as some super admin features for controlling and monitoring Keboola Connection.  ## Projects Management  * Create, modify and delete maintainers, organizations and projects  * Move projects between organizations  * Define project limits  * Provision Redshift and other Storage backends  * Access project management activity log  ## Projects Monitoring  * Monitoring of projects over organizations and maintainers  ## Super User Control and Monitoring  * UI release and deployment  * Components management  * Storage and Syrup jobs monitoring (will be provided by Syrup utilizing new tokens for authorization)  * Final project delete  * Workers start/shutdown, etc.  ## Authentication  The API supports authentication by a personal access token, which can be retrieved in [Account Settings](https://connection.keboola.com/admin/account/change-password) in Keboola Connection. An access token is tied to an administrator and its permissions are derived from their permissions. When the administrator is disabled or deleted, all their tokens become invalid too.  ## Token Types  There are the following types of tokens:  | Name | Tied to User | Token string is available only on create | Description  | | ------------- | ------------- | ------------------- | ----- | | user | Yes | Yes |Full access to maintainers, organizations and projects. Access is limited only to resources which are available for the token user.| | super | No | Yes | KBC management. Limited scopes can be specified `super_ui_deploy`, `super_monitoring`, ...  |

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BigQueryStorageBackendCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BigQueryStorageBackendCreate{}

// BigQueryStorageBackendCreate struct for BigQueryStorageBackendCreate
type BigQueryStorageBackendCreate struct {
	// associated GCP account owner
	Owner string `json:"owner"`
	// where is service account created
	FolderId string `json:"folderId"`
	Region string `json:"region"`
	Credentials *GCPCredentials `json:"credentials,omitempty"`
}

type _BigQueryStorageBackendCreate BigQueryStorageBackendCreate

// NewBigQueryStorageBackendCreate instantiates a new BigQueryStorageBackendCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBigQueryStorageBackendCreate(owner string, folderId string, region string) *BigQueryStorageBackendCreate {
	this := BigQueryStorageBackendCreate{}
	this.Owner = owner
	this.FolderId = folderId
	this.Region = region
	return &this
}

// NewBigQueryStorageBackendCreateWithDefaults instantiates a new BigQueryStorageBackendCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBigQueryStorageBackendCreateWithDefaults() *BigQueryStorageBackendCreate {
	this := BigQueryStorageBackendCreate{}
	return &this
}

// GetOwner returns the Owner field value
func (o *BigQueryStorageBackendCreate) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *BigQueryStorageBackendCreate) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *BigQueryStorageBackendCreate) SetOwner(v string) {
	o.Owner = v
}

// GetFolderId returns the FolderId field value
func (o *BigQueryStorageBackendCreate) GetFolderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FolderId
}

// GetFolderIdOk returns a tuple with the FolderId field value
// and a boolean to check if the value has been set.
func (o *BigQueryStorageBackendCreate) GetFolderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FolderId, true
}

// SetFolderId sets field value
func (o *BigQueryStorageBackendCreate) SetFolderId(v string) {
	o.FolderId = v
}

// GetRegion returns the Region field value
func (o *BigQueryStorageBackendCreate) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *BigQueryStorageBackendCreate) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *BigQueryStorageBackendCreate) SetRegion(v string) {
	o.Region = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *BigQueryStorageBackendCreate) GetCredentials() GCPCredentials {
	if o == nil || IsNil(o.Credentials) {
		var ret GCPCredentials
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BigQueryStorageBackendCreate) GetCredentialsOk() (*GCPCredentials, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *BigQueryStorageBackendCreate) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given GCPCredentials and assigns it to the Credentials field.
func (o *BigQueryStorageBackendCreate) SetCredentials(v GCPCredentials) {
	o.Credentials = &v
}

func (o BigQueryStorageBackendCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BigQueryStorageBackendCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["owner"] = o.Owner
	toSerialize["folderId"] = o.FolderId
	toSerialize["region"] = o.Region
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

func (o *BigQueryStorageBackendCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"owner",
		"folderId",
		"region",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBigQueryStorageBackendCreate := _BigQueryStorageBackendCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBigQueryStorageBackendCreate)

	if err != nil {
		return err
	}

	*o = BigQueryStorageBackendCreate(varBigQueryStorageBackendCreate)

	return err
}

type NullableBigQueryStorageBackendCreate struct {
	value *BigQueryStorageBackendCreate
	isSet bool
}

func (v NullableBigQueryStorageBackendCreate) Get() *BigQueryStorageBackendCreate {
	return v.value
}

func (v *NullableBigQueryStorageBackendCreate) Set(val *BigQueryStorageBackendCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableBigQueryStorageBackendCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableBigQueryStorageBackendCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBigQueryStorageBackendCreate(val *BigQueryStorageBackendCreate) *NullableBigQueryStorageBackendCreate {
	return &NullableBigQueryStorageBackendCreate{value: val, isSet: true}
}

func (v NullableBigQueryStorageBackendCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBigQueryStorageBackendCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


